"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import styles from "./Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [position, setPosition] = useState({ x: 0, y: 0 });
  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      setPosition({ x: event.clientX, y: event.clientY });
    };

    document.addEventListener("mousemove", handleMouseMove);

    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);
  return (
    <html lang="en">
      <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
      </head>
      <body className={inter.className} style={{ backgroundColor: "#1E0342", overflowX: "hidden" }} >
        <div
          style={{
            position: "fixed",
            top: position.y,
            left: position.x,
            width: "800px",
            height: "800px",
            borderRadius: "50%",
            backgroundColor: "#E1F7F5",
            filter: "blur(110px)",
            transform: "translate(-50%, -50%)",
            pointerEvents: "none",
            opacity: 0.1,
            transition: "all 0.2s",
          }}
        />

        <div className={`container ${styles.container} ml-5`} style={{overflow: "hidden"}}>{children}</div>
        
      </body>
    </html>
  );
}
